### ISSUE TITLE
Supply a release version

### ISSUE THREAD

**Issue by Razzeee** [gessnerfl/rabbitmq-queue-management#1]
Hey there, 

is this project in a runnable state and can you release a compiled version if so?

Cheers

**Comment by gessnerfl** [comment]
Hi Razzeee,

absolutely, this project is in a runnable state.
I will try to deploy a compiled version by this week and will let you know as soon it is available.

Greets

**Comment by gessnerfl** [comment]
You can now download the compiled release from Github 
https://github.com/gessnerfl/rabbitmq-queue-management/releases
