### ISSUE TITLE
Bootstrap UI: migrate to v5 

### ISSUE THREAD

**Issue by PyMichaelB** [gessnerfl/rabbitmq-queue-management#54]
Hi,

I've noticed that while a Bootstrap version bump has been made to parts of the project, it has not been completed.

Two issues:
1) While the webjars dependency in build.gradle has been changed from v4 to v5, not all HTML pages have incorporated this change - only **index.html**
2) Some HTML pages require syntax change due to these version changes

This leads to some pages with styling that has been affected e.g.

**index.html** - version bump made, but syntax out of date
Bootstrap v4:
![image](https://user-images.githubusercontent.com/16258190/190917453-5c4595e0-8068-4b20-a466-14fbdab233a5.png)

Bootstrap v5 without syntax upgrades:
![image](https://user-images.githubusercontent.com/16258190/190917375-03319ee4-9da9-454b-8db5-03684fe6be27.png)

**messages.html** - version bump not made, some syntax out of date as well
Bootstrap v4:
![image](https://user-images.githubusercontent.com/16258190/190917581-6b91b1e9-2258-4fef-8770-4512b4de38cb.png)

Bootstrap v5:
![image](https://user-images.githubusercontent.com/16258190/190917607-0c8d6811-5406-4732-b544-de9b543bc300.png)

**Comment by gessnerfl** [comment]
@PyMichaelB thanks for your contribution. I merged the PR into an intermediate branch. I will cross check the changes asap before merging it into main code line

**Comment by gessnerfl** [comment]
Fixed with version 1.2.0
